// lib/cities.ts
//
// Top 50 US metros + major international cities for waitlist city picker.
// Sorted alphabetically within each group.
// Update this list as you identify target launch cities.

export const CITIES: string[] = [
  // ── US Metros ──
  "Atlanta, GA",
  "Austin, TX",
  "Baltimore, MD",
  "Boston, MA",
  "Charlotte, NC",
  "Chicago, IL",
  "Cincinnati, OH",
  "Cleveland, OH",
  "Columbus, OH",
  "Dallas, TX",
  "Denver, CO",
  "Detroit, MI",
  "Hartford, CT",
  "Houston, TX",
  "Indianapolis, IN",
  "Jacksonville, FL",
  "Kansas City, MO",
  "Las Vegas, NV",
  "Los Angeles, CA",
  "Louisville, KY",
  "Memphis, TN",
  "Miami, FL",
  "Milwaukee, WI",
  "Minneapolis, MN",
  "Nashville, TN",
  "New Orleans, LA",
  "New York, NY",
  "Oklahoma City, OK",
  "Orlando, FL",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Pittsburgh, PA",
  "Portland, OR",
  "Raleigh, NC",
  "Richmond, VA",
  "Sacramento, CA",
  "Salt Lake City, UT",
  "San Antonio, TX",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Seattle, WA",
  "St. Louis, MO",
  "Tampa, FL",
  "Virginia Beach, VA",
  "Washington, DC",

  // ── International ──
  "Amsterdam, Netherlands",
  "Auckland, New Zealand",
  "Bangkok, Thailand",
  "Barcelona, Spain",
  "Berlin, Germany",
  "Bogotá, Colombia",
  "Buenos Aires, Argentina",
  "Cairo, Egypt",
  "Cape Town, South Africa",
  "Dubai, UAE",
  "Dublin, Ireland",
  "Hong Kong",
  "Istanbul, Turkey",
  "Jakarta, Indonesia",
  "Kuala Lumpur, Malaysia",
  "Lagos, Nigeria",
  "Lima, Peru",
  "Lisbon, Portugal",
  "London, UK",
  "Madrid, Spain",
  "Manila, Philippines",
  "Melbourne, Australia",
  "Mexico City, Mexico",
  "Milan, Italy",
  "Montreal, Canada",
  "Mumbai, India",
  "Nairobi, Kenya",
  "Paris, France",
  "São Paulo, Brazil",
  "Seoul, South Korea",
  "Singapore",
  "Stockholm, Sweden",
  "Sydney, Australia",
  "Tel Aviv, Israel",
  "Tokyo, Japan",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Vienna, Austria",
  "Warsaw, Poland",
  "Zurich, Switzerland",
];
